#define SYS_open      0
#define SYS_close     1
#define SYS_read      2
#define SYS_write     3
#define SYS_seek      4
#define SYS_lseek     5
#define SYS_stat      6
#define SYS_fstat     7
#define SYS_readdir   8
#define SYS_dup       9
#define SYS_mount    10
#define SYS_chmain   11
